FROM scratch

LABEL org.opencontainers.image.title="LyraNest Community Server" \
      org.opencontainers.image.version="1.0.1"

COPY bin/music-player-server-linux-amd64 /usr/local/bin/music-player-server

ENV SERVER_ADDR=:8080 \
    GOMEMLIMIT=192MiB \
    GOGC=100
EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/music-player-server"]
